/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liufeismart_jni_hellojni_HelloJNI */

#ifndef _Included_com_liufeismart_jni_hellojni_HelloJNI
#define _Included_com_liufeismart_jni_hellojni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_helloJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    setName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_setName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    getArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_getArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
