/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liufeismart_jni_hellojni_HelloJNI */

#ifndef _Included_com_liufeismart_jni_hellojni_HelloJNI
#define _Included_com_liufeismart_jni_hellojni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_helloJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_liufeismart_jni_hellojni_HelloJNI
 * Method:    add
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_com_liufeismart_jni_hellojni_HelloJNI_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
